[project]
name = "sparv-sbx-emotional-classification-workspace"
dependencies = []
requires-python = ">=3.8.1,<3.12"
version = "0.0.0"

[tool.pdm.dev-dependencies]
dev = [
    "-e sparv-sbx-sentence-emotional-classification-kb-emoclass @ file:///${PROJECT_ROOT}/sparv-sbx-sentence-emotional-classification-kb-emoclass",
    "pytest>=8.1.1",
    "pytest-cov>=4.1.0",
    "mypy>=1.9.0",
    "ruff>=0.4.5",
    "syrupy>=4.6.1",
    "sparv-pipeline-testing @ git+https://github.com/spraakbanken/sparv-pipeline-testing.git@v0.1.5",
    "bump-my-version>=0.25.4",
]
